// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroDEeTecnico.DAL;

#nullable disable

namespace RegistroDEeTecnico.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20240527152828_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("RegistroDEeTecnico.Models.IncentivosTecnicos", b =>
                {
                    b.Property<int>("IncentivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadServicios")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<int>("TecnicoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IncentivoId");

                    b.ToTable("IncentivosTecnicos");
                });

            modelBuilder.Entity("RegistroDEeTecnico.Models.Tecnicos", b =>
                {
                    b.Property<int>("TecnicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("SueldoHora")
                        .HasColumnType("REAL");

                    b.Property<int>("tipoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("tiposTecnicotipoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TecnicoId");

                    b.HasIndex("tiposTecnicotipoId");

                    b.ToTable("Tecnicos");
                });

            modelBuilder.Entity("RegistroDEeTecnico.Models.TiposTecnicos", b =>
                {
                    b.Property<int>("tipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("tipoId");

                    b.ToTable("TiposTecnicos");
                });

            modelBuilder.Entity("RegistroDEeTecnico.Models.Tecnicos", b =>
                {
                    b.HasOne("RegistroDEeTecnico.Models.TiposTecnicos", "tiposTecnico")
                        .WithMany()
                        .HasForeignKey("tiposTecnicotipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tiposTecnico");
                });
#pragma warning restore 612, 618
        }
    }
}
